### ISSUE TITLE
Google Login Button

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-app#143]
## Docs
https://developers.google.com/identity/sign-in/web/sign-in
https://developers.google.com/identity/sign-in/web/reference

## Todo
- [x] Setup Credentials in GCP https://console.developers.google.com/apis/credentials
- [ ] Setup Project Gmail, e.g. `satzbeleg@gmail.com`
- [x] Add script tag to HTML ~~add google npm pkg to app~~
    1. [x] Add script to HTML window from .vue file
    2. Call window.gapi within .vue file
    - https://stackoverflow.com/questions/60367946/how-to-add-google-authentication-to-vue-js-using-typescript-and-component-style
    - ~~The @types/gapi solution: https://gist.github.com/jakekara/652e3c3bf272cd682ae39b50f1c45062~~
- [x] add official btn to login and signup View
- [x] add signinGoogle function to axios-evidence.js (retrieve gid, and upsert to get existing/new user_id)
- [x] SQL table to store gid and create new user_id https://github.com/satzbeleg/evidence-database/issues/48
- [x] connect REST API https://github.com/satzbeleg/evidence-restapi/issues/63
- [x] add Google Sign Out to logout function (check if user_id has gid, if yes post google signout rrquest)
