### ISSUE TITLE
domain/#/privacy Page

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-app#164]
https://evidence.bbaw.de/#/legal/privacy

## TODO
- [x] write privacy policy (Datenschutz)
- [ ] i18n translattions
- [x] fix broken hyperlinks
- [x] use an html template
