### ISSUE TITLE
Prepare public status on Github

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-app#167]
### Assessment
- A complete rebase is required because real usernames and passwords were hardcoded at some point.

### TODO
- [x] Scan for security leaks
    - [x] passed: `truffleHog --regex --entropy=False https://github.com/satzbeleg/evidence-app.git` 
    - [x] passed, only old toy credentials that have been removed `gittyleaks -link https://github.com/satzbeleg/evidence-app`
- [ ] Delete unnecessary comments and code
- [x] Translate comments/readme to EN
- [ ] Replace Demo sentences with CC-BY-* sentence examples
- [ ] Transfer the whole repo to a backup location (incl. issues)
- [ ] Create a new repo with a clean code version as initial upload
