### ISSUE TITLE
persistent storage of user-specific TFJS models

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-app#196]
User Story: As [user] I need to store the latest TFJS model checkpoint in the backend server, so that I could restart my app lateron.

## TODO
- [x] POST: Specify REST endpoint to dump the latest TFJS model, https://www.tensorflow.org/js/guide/save_load#https_request
- [ ] DELETE: Reset store TFJS model
- [x] GET: Download the TFJS model, Fetch method needed, https://www.tensorflow.org/js/guide/save_load#https

## Coding
- only if `has_data_donation_consent`
- in `interactivity.js/getTfjsModel` try to load (1) model from IndexDB, (2) persistent model from DB, or (3) the baseline model
