### ISSUE TITLE
delete account button

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-app#219]
### TODO
- [ ] REST API call => Has immediate effect
- [ ] User has to type his email to confirm the account deletion
- [ ] Big warning that the account deletion is executed immediatly
