### ISSUE TITLE
[5] Korrekturlesen Impressum, Datenschutz

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-app#225]
## TODO
- [x] Informierte Einwilligung (consent), https://github.com/satzbeleg/evidence-app/blob/main/src/translations/pages/consent-de.vue
- [x] Datenschutz (privacy), https://github.com/satzbeleg/evidence-app/blob/main/src/translations/pages/privacy-de.vue
- [x] IMpressum (imprint), https://github.com/satzbeleg/evidence-app/blob/main/src/translations/pages/imprint-de.vue

https://github.com/satzbeleg/evidence-app/tree/main/src/translations/pages
