### ISSUE TITLE
After registration, open a view to tell the user that s/he should check their E-Mail to verify the account

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-app#227]
## TODO
- [ ] new view with message "Please check your E-Mail account to verify ..."
- [ ] open the view for all accounts that are not verfied yet
- [ ] Button to request a new verfication E-Mail
