### ISSUE TITLE
Refactor Sampling Strategies to JS (Which sentences should be sampled in BWS, before step 3)

### ISSUE THREAD

**Issue by ulf1** [satzbeleg/evidence-app#243]
### TODO
- [ ] refactor `max_uncertainty_sampling`
- [ ] refactor `max_density_sampling`
    - [ ] ~~NPM package for Kernel Density Est.~~ Install https://github.com/uwdata/fast-kde-benchmarks

### Python code
- https://git.zdl.org/wuhn/evidence-sampling-strategies-pseudocode/src/branch/master/sampling_strategies.py

### Notes
- features: the input data
- scores: model scores

**Comment by ulf1** [comment]
don't add more algorithms at this point
